MCLD/ocuda

src/Ops.Models/Abstract/BaseEntity.cs, src/Ops.Models/Section.cs, src/Ops.Models/SectionCalendar.cs, src/Ops.Models/SectionFile.cs, src/Ops.Models/SectionLink.cs, src/Ops.Models/SectionPage.cs, src/Ops.Models/SectionPost.cs, src/Ops.Service/SectionService.cs, src/Utility/Helpers/PaginateTagHelper.cs, src/Utility/Models/PaginateModel.cs, src/Utility/Utility.csproj
- Add models and sample methods
- Add paginate helper
=> Add models and paginate helper

src/Ops.Controllers/RosterController.cs, src/Ops.Controllers/ViewModels/Roster/RosterChangesViewModel.cs, src/Ops.Controllers/ViewModels/Roster/RosterUploadViewModel.cs, src/Ops.Models/RosterDetail.cs, src/Ops.Models/RosterEntry.cs, src/Ops.Service/Ops.Service.csproj, src/Ops.Service/RosterService.cs, src/Ops.Web/Startup.cs, src/Ops.Web/Views/Roster/Changes.cshtml, src/Ops.Web/Views/Roster/Upload.cshtml
- Add Roster Views and ViewModels
- Update Roster Controller and Service
=> Add Ops Roster Views

src/Ops.Controllers/SectionController.cs, src/Ops.Controllers/ViewModels/Section/AdminDetailViewModel.cs, src/Ops.Controllers/ViewModels/Section/SectionListViewModel.cs, src/Ops.Service/SectionService.cs, src/Ops.Web/Views/Section/AdminDetail.cshtml, src/Ops.Web/Views/Section/Index.cshtml
- Add Section Controller, ViewModels, Views
- Update SectionService
=> Add Section Management

src/Ops.Controllers/DebugController.cs, src/Ops.Data/Ops/UserRepository.cs, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.Models/Section.cs, src/Ops.Service/FileService.cs, src/Ops.Service/Filters/BaseFilter.cs, src/Ops.Service/InitialSetupService.cs, src/Ops.Service/InsertSampleDataService.cs, src/Ops.Service/Interfaces/Ops/ISectionRepository.cs, src/Ops.Service/Interfaces/Ops/IUserRepository.cs, src/Ops.Service/LinkService.cs, src/Ops.Service/Models/DateWithCount.cs, src/Ops.Service/PageService.cs, src/Ops.Service/PostService.cs, src/Ops.Service/SectionService.cs, src/Ops.Service/UserService.cs, src/Ops.Web/StartupHelper/DataContext.cs, src/Ops.Web/Views/Shared/_Layout.cshtml
- Add insert sample data button
=> Add insert sample data button

.travis.yml, dev/bin/docker-build.sh
Split Travis build into two jobs
=> Improve Travis build with jobs

src/Ops.Controllers/Areas/Admin/SiteSettingsController.cs, src/Ops.Controllers/Areas/Admin/ViewModels/SiteSettings/IndexViewModel.cs, src/Ops.Data/Ops/SiteSettingRepository.cs, src/Ops.Models/SiteSetting.cs, src/Ops.Service/InsertSampleDataService.cs, src/Ops.Service/Interfaces/Ops/ISiteSettingRepository.cs, src/Ops.Service/SiteSettingService.cs, src/Ops.Web/Areas/Admin/Views/SiteSettings/Index.cshtml, src/Ops.Web/Startup.cs, src/Ops.Web/Views/Home/Unauthorized.cshtml
- Adds SiteSettings View, Controller, and Service
- Updates SiteSettings Model and Repository
- Adds sample SiteSettings in InsertSampleDataService
- Updates Unauthorized view page.
=> Add SiteSettings Feature

src/Ops.Controllers/Abstract/BaseController.cs, src/Ops.Controllers/Areas/Admin/FilesController.cs, src/Ops.Controllers/Areas/Admin/LinksController.cs, src/Ops.Controllers/Areas/Admin/PagesController.cs, src/Ops.Controllers/Areas/Admin/PostsController.cs, src/Ops.Controllers/Areas/Admin/RosterController.cs, src/Ops.Controllers/Areas/Admin/SectionsController.cs, src/Ops.Controllers/Areas/Admin/SiteSettingsController.cs, src/Ops.Controllers/ErrorController.cs, src/Ops.Controllers/FilesController.cs, src/Ops.Controllers/HomeController.cs, src/Ops.Controllers/LinksController.cs, src/Ops.Controllers/PagesController.cs, src/Ops.Controllers/PostsController.cs, src/Ops.Controllers/ProfileController.cs, src/Ops.Controllers/ServiceFacade/Controller.cs, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Startup.cs
- Add ServiceFacade with SiteSettingService and ILogger
=> Add ServiceFacade for controllers

src/Ops.Service/CategoryService.cs, src/Ops.Service/InsertSampleDataService.cs, src/Ops.Service/SectionService.cs, test/Ops/Ops.Service.Test/SectionService_Tests.cs
- Add default file and link categories when a section is created.
- Update InsertSampleDataService.
=> Update Default Categories

src/Ops.Web.WindowsAuth/Startup.cs, src/Ops.Web/Startup.cs, src/Utility/Keys/Cache.cs
Fix issue with inconsistent namespacing in distributed cache
=> Fix namespacing for distributed cache

src/Ops.Data/Ops/SectionRepository.cs, src/Ops.Models/Section.cs, src/Ops.Service/SectionService.cs
- Add IsDeleted field to Section Model
- Update service method to set IsDeleted field instead of removing the section
- Update repository search methods to exclude deleted Sections
=> Update Section Deletion

src/Ops.Controllers/Areas/Admin/SectionsController.cs, src/Ops.Controllers/HomeController.cs, src/Ops.Controllers/ViewModels/Home/IndexViewModel.cs, src/Ops.Models/Section.cs, src/Ops.Service/Interfaces/Ops/Services/ISectionService.cs, src/Ops.Service/SectionService.cs, src/Ops.Web/Areas/Admin/Views/Sections/Detail.cshtml, src/Ops.Web/Views/Home/Index.cshtml
- Add Featured Video card to sidebar on Home page
- Allow editing featured video url from card header or section edit page
=> Add Featured Video

src/Ops.Controllers/Areas/Admin/RosterController.cs, src/Ops.Controllers/Filters/AuthenticationFilter.cs, src/Ops.Controllers/Filters/UserFilter.cs, src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Controllers/ProfileController.cs, src/Ops.Data/Ops/UserRepository.cs, src/Ops.Models/RosterDetail.cs, src/Ops.Models/User.cs, src/Ops.Service/Interfaces/Ops/Repositories/IUserRepository.cs, src/Ops.Service/Interfaces/Ops/Services/ILdapService.cs, src/Ops.Service/Interfaces/Ops/Services/IUserService.cs, src/Ops.Service/LdapService.cs, src/Ops.Service/Ops.Service.csproj, src/Ops.Service/RosterService.cs, src/Ops.Service/UserService.cs, src/Ops.Web/Startup.cs
=> Add user importing

src/Ops.Controllers/Abstract/BaseController.cs, src/Ops.Controllers/ProfileController.cs, src/Ops.Controllers/ViewModels/Profile/IndexViewModel.cs, src/Ops.Data/Ops/UserRepository.cs, src/Ops.Service/Interfaces/Ops/Repositories/IUserRepository.cs, src/Ops.Service/Interfaces/Ops/Services/IUserService.cs, src/Ops.Service/UserService.cs, src/Ops.Web/Views/Profile/Index.cshtml
- Fix username lookup to use HttpContext.User.Identity.Name
- Fetch and show direct reports on profile page
- Link supervisor and direct reports on profile page to their profile
- Fix formatting
=> Improve user profile view

src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web.WindowsAuth/Program.cs
- Add RuntimeFrameworkVersion to WindowsAuth .csproj
- Customizable rolling log file path
=> Fix WindowsAuth build, improve logging

src/Ops.Web.WindowsAuth/Program.cs
- Need to create WebHostBuilder once logging has been added
=> Fix WindowsAuth logging configuration

src/Ops.Controllers/Areas/Admin/ViewModels/Roster/UploadViewModel.cs, src/Ops.Controllers/FilesController.cs, src/Ops.Controllers/LinksController.cs, src/Ops.Data/Ops/FileRepository.cs, src/Ops.Data/Ops/LinkRepository.cs, src/Ops.Models/Entities/Section.cs, src/Ops.Models/Entities/User.cs, src/Ops.Service/FileService.cs, src/Ops.Service/Interfaces/Ops/Repositories/IFileRepository.cs, src/Ops.Service/Interfaces/Ops/Repositories/ILinkRepository.cs, src/Ops.Service/Interfaces/Ops/Services/IFileService.cs, src/Ops.Service/Interfaces/Ops/Services/ILinkService.cs, src/Ops.Service/LdapService.cs, src/Ops.Service/LinkService.cs, src/Ops.Service/RosterService.cs, src/Ops.Service/SectionService.cs, src/Ops.Web/Areas/Admin/Views/Roster/Upload.cshtml, src/Ops.Web/Areas/Admin/Views/Sections/Detail.cshtml, src/Ops.Web/Areas/Admin/Views/Sections/Index.cshtml, src/Ops.Web/Views/Home/Index.cshtml
- Add embedded video to section
- Add file and link latest entry
- Update roster uploading
=> Add layout improvements

src/Promenade.Controllers/Filters/NavigationFilter.cs, src/Promenade.Controllers/ItemKey.cs, src/Promenade.Models/Defaults/SiteSetting.cs, src/Promenade.Models/Keys/SiteSetting.cs, src/Promenade.Web/Views/Shared/_Layout.cshtml
- Add site setting for Google Analytics
- Add code to add analytics to page if code is set
=> Add Google Analytics to promenade

src/Ops.Service/FeatureService.cs, src/Ops.Web/Areas/SiteManagement/Views/Features/FeatureDetails.cshtml, src/Promenade.Controllers/LocationsController.cs, src/Promenade.Controllers/ViewModels/Locations/LocationsFeaturesViewModel.cs, src/Promenade.Models/Entities/Feature.cs, src/Promenade.Web/Views/Locations/LocationDetails.cshtml
=> Rename FontAwesome to Icon

src/Promenade.Controllers/AboutController.cs, src/Promenade.Controllers/Abstract/BaseController.cs, src/Promenade.Controllers/EmediaController.cs, src/Promenade.Controllers/ErrorController.cs, src/Promenade.Controllers/LocationsController.cs, src/Promenade.Controllers/NewsController.cs, src/Promenade.Controllers/SubjectController.cs, src/Promenade.Models/Defaults/SiteSetting.cs, src/Promenade.Models/Keys/SiteSetting.cs, src/Promenade.Web/Views/Emedia/Index.cshtml, src/Promenade.Web/Views/Error/Index.cshtml, src/Promenade.Web/Views/Locations/LocationDetails.cshtml, src/Promenade.Web/Views/Locations/LocationFeatureDetails.cshtml, src/Promenade.Web/Views/Locations/Locations.cshtml, src/Promenade.Web/Views/Shared/Error.cshtml, src/Promenade.Web/Views/Shared/_Layout.cshtml, src/Utility/Keys/ViewData.cs
=> Add page title suffix

src/Ops.Data/PromenadeContext.cs, src/Ops.Models/Entities/Category.cs, src/Ops.Models/Entities/FileLibrary.cs, src/Ops.Models/Entities/LinkLibrary.cs, src/Ops.Models/Entities/Post.cs, src/Ops.Models/Entities/Section.cs, src/Ops.Models/Entities/SiteSetting.cs, src/Promenade.Data/Promenade/PageRepository.cs, src/Promenade.Data/PromenadeContext.cs, src/Promenade.Models/Entities/Group.cs, src/Promenade.Models/Entities/Location.cs, src/Promenade.Models/Entities/LocationHoursOverride.cs, src/Promenade.Models/Entities/SiteSetting.cs
- Fix EmediaCategory to have a composite key
- Add MaxLength on most string fields
- Set PageHeaders to not be writable from the promenade project
=> Fix database structure

src/Promenade.Data/PromenadeContext.cs
Currently all pages display "Page not found"
This populates the PageHeader in the context
=> Fix pages from not loading on prom

.travis.yml, Dockerfile_promenade, docker-build.bash
- Fix Travis CI branch name detection
- Fix Dockerfile_promenade deployment directory
- Always include remote Docker hostname
- Quote variables in the build script
- Clean up build script per Codacy
=> Improve Docker build

docker-build.bash
- Fix docker-build.bash to support release preparation and release publish external scripts
- Run shell scripts through ShellCheck linter and correct errors
=> Fix and unify Docker build process

src/Promenade.Controllers/TagHelpers/SocialCardTagHelper.cs, src/Promenade.Models/Defaults/SiteSetting.cs, src/Promenade.Models/Keys/SiteSetting.cs, src/Promenade.Service/SocialCardService.cs
- Fix public Twitter card tags
- Improve Twitter site setting to make it clearer
=> Minor fixes to Twitter social configuration

src/Ops.Controllers/AdminController.cs, src/Ops.Controllers/Areas/Admin/PagesController.cs, src/Ops.Controllers/Areas/Admin/SocialCardsController.cs, src/Ops.Controllers/Areas/CoverIssue/ManagementController.cs, src/Ops.Controllers/Areas/CoverIssue/ReportingController.cs, src/Ops.Controllers/Areas/SiteManagement/CategoriesController.cs, src/Ops.Controllers/Areas/SiteManagement/EmediaController.cs, src/Ops.Controllers/Areas/SiteManagement/ExternalResourcesController.cs, src/Ops.Controllers/Areas/SiteManagement/FeatureController.cs, src/Ops.Controllers/Areas/SiteManagement/GroupsController.cs, src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs, src/Ops.Controllers/Areas/SiteManagement/RosterController.cs, src/Ops.Controllers/Areas/SiteManagement/SegmentsController.cs, src/Ops.Controllers/Areas/SiteManagement/SiteSettingsController.cs, src/Ops.Controllers/Areas/SiteManagement/UsersController.cs, src/Ops.Controllers/ContentManagementController.cs, src/Ops.Controllers/CoverIssueController.cs, src/Ops.Controllers/SiteManagementController.cs, src/Ops.Web/Views/Admin/Index.cshtml, src/Ops.Web/Views/ContentManagement/Index.cshtml, src/Ops.Web/Views/CoverIssue/Index.cshtml, src/Ops.Web/Views/SiteManagement/Index.cshtml
Add index pages to Areas in Ops
=> Add Area Index Pages

src/Ops.Service/LocationFeatureService.cs, src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/_EditFeaturesPartial.cshtml, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Startup.cs, src/Promenade.Controllers/ViewModels/Locations/LocationsFeaturesViewModel.cs, src/Promenade.Models/Entities/LocationFeature.cs, src/Promenade.Web/Views/Locations/LocationDetails.cshtml
- Add location feature new tab option
- Add razor runtime compilation to ops
=>  Add location feature new tab option 

src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Service/Ops.Service.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Service/Promenade.Service.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
=> Update to ASP.NET Core 3.1.1

src/Promenade.Data/Promenade/LocationFeatureRepository.cs, src/Promenade.Models/Entities/Feature.cs, src/Promenade.Web/Views/Locations/LocationDetails.cshtml
=> Add feature sorting

src/Ops.Web/Ops.Web.csproj, src/Ops.Web/appsettings.Development.json, src/Ops.Web/appsettings.json, src/Promenade.Web/Promenade.Web.csproj
- Default Ops logging for Microsoft and System namespaces to warning
=> Reduce ops logging

CHANGELOG.md, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/ErrorController.cs, src/Promenade.Web/Promenade.Web.csproj
- Fix redirect query string append
=> Fix redirect query string append

CHANGELOG.md, src/Ops.Data/PromenadeContext.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20200219235619_prom_v1.0.0.11.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20200219235619_prom_v1.0.0.11.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20200219235619_prom_v1.0.0.2.cs.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20200219235619_prom_v1.0.0.2.cs.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/EmediaController.cs, src/Promenade.Controllers/ViewModels/Emedias/EmediaViewModel.cs, src/Promenade.Data/Promenade/EmediaGroupRepository.cs, src/Promenade.Data/PromenadeContext.cs, src/Promenade.Models/Entities/Emedia.cs, src/Promenade.Models/Entities/EmediaGroup.cs, src/Promenade.Service/EmediaService.cs, src/Promenade.Service/Interfaces/Repositories/IEmediaGroupRepository.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Startup.cs, src/Promenade.Web/Views/Emedia/Index.cshtml
- 📇 Includes database changes with migration
- Add emedia grouping
=> Add emedia grouping

CHANGELOG.md, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade/SegmentRepository.cs, src/Promenade.Web/Promenade.Web.csproj
- Fix #157 Fix segment date constraints not working properly
=> Fix segment date constraints not working properly

CHANGELOG.md, src/Ops.Web/Ops.Web.csproj, src/Promenade.Service/Abstract/BaseService.cs, src/Promenade.Service/ExternalResourceService.cs, src/Promenade.Service/LanguageService.cs, src/Promenade.Service/NavigationService.cs, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Keys/Cache.cs
- Add language id caching for default and per-culture lookup
- Change all caching expirations to use a master value
=> Add language id caching; fix cache expiration

CHANGELOG.md, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/Abstract/BasePageController.cs, src/Promenade.Controllers/ErrorController.cs, src/Promenade.Controllers/Filters/LayoutFilter.cs, src/Promenade.Controllers/ItemKey.cs, src/Promenade.Controllers/ViewModels/Shared/PageViewModel.cs, src/Promenade.Data/Promenade/UrlRedirectRepository.cs, src/Promenade.Service/Abstract/BaseService.cs, src/Promenade.Service/Interfaces/Repositories/IUrlRedirectRepository.cs, src/Promenade.Service/PageService.cs, src/Promenade.Service/RedirectService.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Home/Index.cshtml, src/Promenade.Web/Views/Locations/LocationDetails.cshtml, src/Promenade.Web/Views/Shared/Page.cshtml, src/Utility/Keys/Cache.cs, src/Utility/Keys/Configuration.cs
- Add page caching with configurable expiration
- Add redirect caching with configurable expiration
- Add canonical metadata tag to pages
=> Add page, redirect caching; page canonical tag

CHANGELOG.md, src/Promenade.Controllers/LocationsController.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Locations/LocationDetails.cshtml
- Fix location features modal caching the same description for all
=> Fix location feature caching

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/HelpController.cs, src/Promenade.Web/Promenade.Web.csproj
- Causing issues with /about/help page routing
=> Remove culture from HelpController

CHANGELOG.md, src/Ops.Controllers/Areas/ContentManagement/SectionController.cs, src/Ops.Controllers/HomeController.cs, src/Ops.Controllers/ViewModels/Home/IndexViewModel.cs, src/Ops.Data/Ops/PostRepository.cs, src/Ops.Service/Filters/BlogFilter.cs, src/Ops.Service/Interfaces/Ops/Repositories/IPostRepository.cs, src/Ops.Service/Interfaces/Ops/Services/IPostService.cs, src/Ops.Service/PostService.cs, src/Ops.Web/Views/Home/Index.cshtml
=> Add posts to ops homepage

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/HelpController.cs, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Extensions/DateTimeExtensions.cs
Allow same-day scheduling but enforce a four-hour window between the current time and the schedule time.
=> Add same-day scheduling with a window

src/Ops.Service/Abstract/BaseService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/Abstract/BasePageController.cs, src/Promenade.Controllers/EmediaController.cs, src/Promenade.Controllers/HelpController.cs, src/Promenade.Controllers/LocationsController.cs, src/Promenade.Data/Promenade/CategoryRepository.cs, src/Promenade.Data/Promenade/EmediaCategoryRepository.cs, src/Promenade.Data/Promenade/EmediaGroupRepository.cs, src/Promenade.Data/Promenade/EmediaRepository.cs, src/Promenade.Service/Abstract/BaseService.cs, src/Promenade.Service/EmediaService.cs, src/Promenade.Service/Interfaces/Repositories/ICategoryRepository.cs, src/Promenade.Service/Interfaces/Repositories/IEmediaCategoryRepository.cs, src/Promenade.Service/Interfaces/Repositories/IEmediaGroupRepository.cs, src/Promenade.Service/PageService.cs, src/Promenade.Service/SegmentService.cs, src/Promenade.Service/SocialCardService.cs, src/Promenade.Web/DbLoggingInterceptor.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Startup.cs, src/Utility/Keys/Cache.cs, src/i18n/Filter/LocalizationFilterAttribute.cs
- Remove unnecessary assignment of HttpContext to variable
- Add caching to Social Cards
- Add caching to Emedia
- Add caching to Segments
- Add abstract caching capabilities to base service
- Add database logging interceptor to log SQL calls in debug
=> Increase SQL logging and site caching

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/HelpController.cs, src/Promenade.Service/ScheduleService.cs, src/Promenade.Web/Promenade.Web.csproj
- Fix auto date population on schedule form to work properly on Fridays when it's too late in the day to schedule an appointment
=> Fix auto date population on schedule form

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/HelpController.cs, src/Promenade.Controllers/ViewModels/Help/ScheduleViewModel.cs, src/Promenade.Data/Promenade/LocationHoursOverrideRepository.cs, src/Promenade.Service/Interfaces/Repositories/ILocationHoursOverrideRepository.cs, src/Promenade.Service/LocationService.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Help/Schedule.cshtml
- Properly handle if TempData disappears before submit
- Make all-location closure dates unavailable for booking
=> Add schedule timeout handling and closure dates

src/Ops.Controllers/Areas/Contact/ScheduleController.cs, src/Ops.Controllers/ViewModels/Contact/ScheduleDetailViewModel.cs, src/Ops.Data/Ops/EmailSetupTextRepository.cs, src/Ops.Data/Ops/ScheduleLogRepository.cs, src/Ops.Data/Promenade/ScheduleRequestRepository.cs, src/Ops.Models/Entities/ScheduleLog.cs, src/Ops.Service/Interfaces/Ops/Services/IScheduleRequestService.cs, src/Ops.Service/Interfaces/Ops/Services/IScheduleService.cs, src/Ops.Service/ScheduleNotificationService.cs, src/Ops.Service/ScheduleRequestService.cs, src/Ops.Service/ScheduleService.cs, src/Ops.Service/UserService.cs, src/Ops.Web/Areas/Contact/Views/Schedule/Details.cshtml, src/Ops.Web/Areas/Contact/Views/Schedule/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Service/ScheduleService.cs, src/Promenade.Web/Promenade.Web.csproj
- Show sent emails in schedule request log
- Add unclaim button and functionality
- Add claim and unclaim actions to schedule request log
- Fix bug with tracked items and sending emails
- Show user information in schedule request log
=> Improve schedule request administration

src/Ops.Controllers/Areas/Contact/ScheduleController.cs, src/Ops.Controllers/ViewModels/Contact/ScheduleDetailViewModel.cs, src/Ops.Controllers/ViewModels/Contact/ScheduleIndexViewModel.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20200701171126_ops_v1.0.0.47.Designer.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20200701171126_ops_v1.0.0.47.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20200701171521_prom_v1.0.0.47.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20200701171521_prom_v1.0.0.47.cs, src/Ops.Models/Entities/ScheduleLog.cs, src/Ops.Service/EmailService.cs, src/Ops.Service/Interfaces/Ops/Services/IEmailService.cs, src/Ops.Service/Interfaces/Ops/Services/IScheduleNotificationService.cs, src/Ops.Service/Interfaces/Ops/Services/IScheduleRequestService.cs, src/Ops.Service/Interfaces/Ops/Services/IScheduleService.cs, src/Ops.Service/ScheduleNotificationService.cs, src/Ops.Service/ScheduleRequestService.cs, src/Ops.Service/ScheduleService.cs, src/Ops.Web/Areas/Contact/Views/Schedule/Details.cshtml, src/Ops.Web/Areas/Contact/Views/Schedule/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/ViewModels/Help/ScheduleDetailsViewModel.cs, src/Promenade.Models/Entities/ScheduleRequest.cs, src/Promenade.Models/Entities/ScheduleRequestSubject.cs, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Email/Record.cs, src/Utility/Email/Sender.cs
- Add follow-up email capability for scheduled appointments
- Add additional colors and icons for list of scheduled appointments
=> Add follow-up email; add icons and colors to list

src/Ops.Data/Ops/EmailTemplateTextRepository.cs, src/Ops.Service/ScheduleNotificationService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- If requested email setup or template language is missing, substitute
in the current execution environment default
=> Fix notifications for missing languages

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/PodcastsController.cs, src/Promenade.Web/Promenade.Web.csproj
=> Fix podcast RSS Urls

src/Ops.Controllers/Areas/SiteManagement/PagesController.cs, src/Ops.Web/Areas/Contact/Views/Schedule/Details.cshtml, src/Ops.Web/Areas/ContentManagement/Views/Roster/Upload.cshtml, src/Ops.Web/Areas/ContentManagement/Views/Section/Section.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Categories/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Emedia/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Features/FeatureDetails.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Features/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Groups/GroupDetails.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Groups/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Pages/Detail.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Pages/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Pages/LayoutDetail.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Pages/Layouts.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Podcasts/EpisodeDetails.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Fix page editing permissions, layout
- Standardize reference to spinner buttons
=> Fix page editing permissions, layout

src/Ops.Web/Ops.Web.csproj, src/Promenade.Service/CarouselService.cs, src/Promenade.Web/Promenade.Web.csproj
- Fix carousel button to use url template
=> Fix carousel button to use url template

.github/workflows/codeql-analysis.yml, .github/workflows/dotnet-outdated.yml, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Update reference to test dependency
- Update GitHub actions
=> Update reference to test dependency

Dockerfile_ops, Dockerfile_promenade, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/AboutController.cs, src/Promenade.Controllers/Filters/LayoutFilter.cs, src/Promenade.Controllers/HomeController.cs, src/Promenade.Controllers/ItemKey.cs, src/Promenade.Controllers/NewsController.cs, src/Promenade.Controllers/SubjectController.cs, src/Promenade.Service/PageService.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Startup.cs, src/Promenade.Web/Views/Shared/_Layout.cshtml, src/i18n/Culture.cs, src/i18n/Filter/LocalizationFilterAttribute.cs, src/i18n/LocalizationItemKey.cs
- Fix culture selection by QueryString
- Disable culture selection by route path
- Fix page display to work properly with culture selection
=> Improve i18n

Dockerfile_ops, Dockerfile_promenade
- The certificate issue appears fixed (NuGet/Announcements#49)
=> Revert Docker sdk image

src/Ops.Controllers/Areas/SiteManagement/EmediaController.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/EmediaController.cs, src/Promenade.Controllers/ViewModels/Emedias/EmediaViewModel.cs, src/Promenade.Models/Defaults/SiteSetting.cs, src/Promenade.Models/Keys/SiteSetting.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Emedia/Index.cshtml, test/i18n/i18n.Test/i18n.Test.csproj
- Update package: coverlet.collector 3.0.1 -> 3.0.2
=> Add social card to eMedia page

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/HelpController.cs, src/Promenade.Web/Promenade.Web.csproj
- Fix scheduling ignoring buffer time
=> Fix scheduling ignoring buffer time

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/HelpController.cs, src/Promenade.Controllers/ViewModels/Help/ScheduleTimesViewModel.cs, src/Promenade.Controllers/ViewModels/Help/ScheduleViewModel.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Help/Schedule.cshtml, src/Promenade.Web/Views/Help/ScheduleTimes.cshtml
- Change scheduling time selection to dropdown list
=> Change scheduling time selection to dropdown list

src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Service/Ops.Service.csproj, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/Promenade.Controllers.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Models/Promenade.Models.csproj, src/Promenade.Service/Promenade.Service.csproj, src/Promenade.Web/Promenade.Web.csproj, src/SlideUploader/SlideUploader.csproj, src/Utility/Helpers/VersionHelper.cs, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Update .NET dependency packages
- Simplify project versioning
=> Update packages; simplify versioning

Dockerfile_ops, Dockerfile_promenade, src/Ops.Controllers/Areas/ContentManagement/DigitalDisplaysController.cs, src/Ops.Data/Ops/DigitalDisplayAssetRepository.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20210407030925_ops_v1.0.0.100.Designer.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20210407030925_ops_v1.0.0.100.cs, src/Ops.Models/Entities/DigitalDisplayAsset.cs, src/Ops.Service/DigitalDisplayService.cs, src/Ops.Service/Interfaces/Ops/Repositories/IDigitalDisplayAssetRepository.cs, src/Ops.Service/Interfaces/Ops/Services/IDigitalDisplayService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Add digital display duplicate image check
- Remove unused model state marshalling
=> Add digital display duplicate image check

src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web.WindowsAuth/Program.cs, src/Ops.Web.WindowsAuth/Startup.cs
- Update to latest C# language revision
- Use same logging interface as Ops/Promenade
- Error page for inability to authenticate
- Modify whoami command to output JSON
=> Update WindowsAuth project to v1.1.0

src/SlideUploader/Program.cs, src/SlideUploader/Upload.cs
- Fix .json save/load filepaths
- Fix exception always being thrown
=> Fix slide uploader indesign compatibility

src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs, src/Ops.Controllers/Areas/SiteManagement/SegmentsController.cs, src/Ops.Controllers/Areas/SiteManagement/SocialCardsController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Location/LocationViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Segment/DetailViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/SocialCards/DetailViewModel.cs, src/Ops.Data/Promenade/SegmentRepository.cs, src/Ops.Service/Interfaces/Ops/Services/ILocationService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/ISegmentRepository.cs, src/Ops.Service/Interfaces/Promenade/Services/ISegmentService.cs, src/Ops.Service/LocationService.cs, src/Ops.Service/SegmentService.cs, src/Ops.Web/Areas/SiteManagement/Views/Locations/Hours.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/StructuredData.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/_LocationPartial.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Segments/Detail.cshtml, src/Ops.Web/Areas/SiteManagement/Views/SocialCards/Detail.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Models/Entities/Location.cs, src/Promenade.Web/Promenade.Web.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Manage location-related segments directly from the location page
- Manage location social cards directly from the location page
=> Improve location editing

src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Service/CarouselService.cs, src/Promenade.Web/Promenade.Web.csproj
- Notify the user when geocoding does not work correctly
- Don't attempt to cache empty carousel information
=> Better geocoding error handling; remove logging

src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/PodcastsController.cs, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.Data/Promenade/PodcastItemRepository.cs, src/Promenade.Data/Promenade/UrlRedirectRepository.cs, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Service/Interfaces/Repositories/IPodcastItemRepository.cs, src/Promenade.Service/PodcastService.cs, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
- Fix podcast episode viewing to limit by podcast
- Improve location management
- Fix redirects if there are multiple configured for the same path
=> Fix podcast episode viewing; other improvements

src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Styles/style.css, src/Promenade.Web/Views/Podcasts/Episode.cshtml, src/Promenade.Web/Views/Podcasts/Index.cshtml, src/Promenade.Web/Views/Podcasts/Podcast.cshtml
- Improves page headings, hides separators from screen reader and, adds descriptor to 3rd party links
=> Add Podcast Accessibility Improvements

src/Ops.Controllers/Areas/ContentManagement/DigitalDisplaysController.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Change slide upload permission requirements
=> Change slide upload permission requirements

src/Ops.Controllers/Areas/SiteManagement/PagesController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Pages/IndexViewModel.cs, src/Ops.Service/ImageFeatureService.cs, src/Ops.Service/Interfaces/Promenade/Services/IPageService.cs, src/Ops.Service/PageService.cs, src/Ops.Web/Areas/SiteManagement/Views/Pages/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Models/Entities/PageHeader.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Shared/_Layout.cshtml, src/Utility/TagHelpers/PaginateTagHelper.cs, test/i18n/i18n.Test/i18n.Test.csproj
Adds aria-labels and, hides necessary objects from screen reader
=> Add pagination accessibility

src/Ops.DataProvider.SqlServer.Promenade/Migrations/20210720220920_prom_v1.0.0.133.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20210720220920_prom_v1.0.0.133.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Models/Entities/Navigation.cs, src/Promenade.Models/Entities/NavigationText.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Shared/_Layout.cshtml
- Remove now-unused aria field from navigation database
- Move navigation links to localized table so they can differ per language
=> Remove nav aria field; allow l10n of nav links

src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Views/Home/Index.cshtml, src/Promenade.Web/Promenade.Web.csproj
- Add home icon to indicate that the post is shown on the home page when viewing a section's posts
=> Add indicator for home section posts

src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Web/Promenade.Web.csproj, src/SlideUploader/SlideUploader.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
- Microsoft.AspNetCore.DataProtection 5.0.11 -> 5.0.12
- Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 5.0.11 -> 5.0.12
- Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 5.0.11 -> 5.0.12
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.11 -> 5.0.12
- Microsoft.EntityFrameworkCore 5.0.11 -> 5.0.12
- Microsoft.EntityFrameworkCore 5.0.11 -> 5.0.12
- Microsoft.EntityFrameworkCore.InMemory 5.0.11 -> 5.0.12
- Microsoft.EntityFrameworkCore.Relational 5.0.11 -> 5.0.12
- Microsoft.EntityFrameworkCore.SqlServer 5.0.11 -> 5.0.12
- Microsoft.EntityFrameworkCore.Tools 5.0.11 -> 5.0.12
- Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore 5.0.11 a-> 5.0.12
- Serilog.Extensions.Logging 3.0.1 -> 3.1.0
=> Update .NET packages

src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/LocationInventoryViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/ProductViewModel.cs, src/Ops.Data/Promenade/ProductLocationInventoryRepository.cs, src/Ops.Data/Promenade/ProductRepository.cs, src/Ops.Data/PromenadeContext.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20211115174008_prom_v1.0.0.154.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20211115174008_prom_v1.0.0.154.cs, src/Ops.Service/Interfaces/Promenade/Repositories/IProductLocationInventoryRepository.cs, src/Ops.Service/Interfaces/Promenade/Repositories/IProductRepository.cs, src/Ops.Service/Interfaces/Promenade/Services/IProductService.cs, src/Ops.Service/ProductService.cs, src/Ops.Web/Areas/SiteManagement/Views/Products/LocationInventory.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Product.cshtml, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Startup.cs, src/Promenade.Data/PromenadeContext.cs, src/Promenade.Models/Entities/Product.cs, src/Promenade.Models/Entities/ProductLocationInventory.cs, src/Promenade.Web/Promenade.Web.csproj
- Add product inventory updating to Ops
- Does not include product management yet
=> Add product inventory updating to Ops

src/Ops.DataProvider.SqlServer.Ops/Migrations/20210730234143_ops_v1.0.0.135.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Migration for ops v1.0.0.135 failed if there was no system user
=> Fix error in migration for v1.0.0.135

build.bash, src/SlideUploader/SlideUploader.csproj, src/Utility/Utility.csproj
- Update build.bash to v1.1.0 to support a test branch
=> Update build script

src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/LocationInventoryViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/MappingViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/ProductViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/UploadViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/VerifyUploadViewModel.cs, src/Ops.Data/Promenade/LocationProductMapRepository.cs, src/Ops.Data/Promenade/LocationRepository.cs, src/Ops.Data/PromenadeContext.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20211206204202_prom_v1.0.0.158.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20211206204202_prom_v1.0.0.158.cs, src/Ops.Service/Interfaces/Ops/Services/ILocationService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/ILocationProductMapRepository.cs, src/Ops.Service/Interfaces/Promenade/Services/IProductService.cs, src/Ops.Service/LocationService.cs, src/Ops.Service/ProductService.cs, src/Ops.Web/Areas/SiteManagement/Views/Products/LocationInventory.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Mapping.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Product.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Upload.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Verify.cshtml, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Startup.cs, src/Promenade.Data/PromenadeContext.cs, src/Promenade.Models/Entities/LocationProductMap.cs, src/Promenade.Models/Entities/ProductLocationInventory.cs, src/Promenade.Web/Promenade.Web.csproj
Add the ability to upload spreadsheets to manage product inventories
=> Add uploadable spreadsheet for product inventory management

src/Ops.Data/Promenade/ProductRepository.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20211222224129_prom_v1.0.0.161.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20211222224129_prom_v1.0.0.161.cs, src/Ops.Service/Interfaces/Promenade/Services/IProductService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/StatusController.cs, src/Promenade.Controllers/ViewModels/Status/ProductInventoryViewModel.cs, src/Promenade.Data/Promenade/ProductInventoryRepository.cs, src/Promenade.Data/Promenade/ProductRepository.cs, src/Promenade.Models/Entities/Product.cs, src/Promenade.Service/Interfaces/Repositories/IProductInventoryRepository.cs, src/Promenade.Service/Interfaces/Repositories/IProductRepository.cs, src/Promenade.Service/ProductService.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Startup.cs, src/Promenade.Web/Views/Status/Product.cshtml, src/Utility/Keys/Cache.cs, src/i18n/Keys/Promenade.cs
- Missing a list of products if there's more than one
- Missing Spanish translations
- Missing ability to configure inventory caching duration
- Missing code to display a segment associated with a product
=> Add a public view of product inventory

src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/DetailsViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/ProductViewModel.cs, src/Ops.Data/Promenade/ProductRepository.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20220118164337_prom_v1.0.0.164.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20220118164337_prom_v1.0.0.164.cs, src/Ops.Service/Interfaces/Promenade/Repositories/IProductRepository.cs, src/Ops.Service/Interfaces/Promenade/Services/IProductService.cs, src/Ops.Service/ProductService.cs, src/Ops.Web/Areas/SiteManagement/Views/Products/Details.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Product.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/StatusController.cs, src/Promenade.Models/Entities/Product.cs, src/Promenade.Models/LocationHoursResult.cs, src/Promenade.Service/LocationService.cs, src/Promenade.Service/ProductService.cs, src/Promenade.Web/Promenade.Web.csproj
- Ability to add/remove locations from product functionality
- Ability to modify inventory caching time per product
- Code to determine when next location status change occurs
=> Add additional product functionality

src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Fix #422 Update ImageSharp package to 2.0.0
=> Update ImageSharp package

src/Ops.Controllers/Areas/SiteManagement/HomeController.cs, src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Home/IndexViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/DetailsViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/IndexViewModel.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Products/PermissionsViewModel.cs, src/Ops.Data/Ops/PermissionGroupProductManagerRepository.cs, src/Ops.Data/OpsContext.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20220407205802_ops_v1.0.0.173.Designer.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20220407205802_ops_v1.0.0.173.cs, src/Ops.Models/Entities/PermissionGroupProductManager.cs, src/Ops.Service/Interfaces/Ops/Repositories/IPermissionGroupProductManagerRepository.cs, src/Ops.Service/Interfaces/Promenade/Services/IProductService.cs, src/Ops.Service/PermissionGroupService.cs, src/Ops.Service/ProductService.cs, src/Ops.Web/Areas/SiteManagement/Views/Home/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Podcasts/Permissions.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Details.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Products/Permissions.cshtml, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Startup.cs, src/Promenade.Models/Entities/Product.cs, src/Promenade.Web/Promenade.Web.csproj
- Add permissions for product management
=> Add product management permissions

src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
Fix bug where looking up product permissions caused an error
=> Fix product permissions lookup

src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs, src/Ops.Service/ProductService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Fix product inventory upload reading empty lines
=> Fix product inventory upload reading empty lines

src/Ops.Controllers/Areas/ContentManagement/UsersController.cs, src/Ops.Controllers/Areas/ContentManagement/ViewModels/Users/TitleClassViewModel.cs, src/Ops.Controllers/Areas/ContentManagement/ViewModels/Users/TitleClassesViewModel.cs, src/Ops.Controllers/ProfileController.cs, src/Ops.Controllers/ViewModels/Profile/IndexViewModel.cs, src/Ops.Data/Ops/TitleClassRepository.cs, src/Ops.Data/Ops/UserRepository.cs, src/Ops.Data/OpsContext.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20220426232145_ops_v1.0.0.182.Designer.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20220426232145_ops_v1.0.0.182.cs, src/Ops.Models/Defaults/SiteSettings.cs, src/Ops.Models/Entities/TitleClass.cs, src/Ops.Models/Entities/TitleClassMapping.cs, src/Ops.Models/Entities/User.cs, src/Ops.Models/Keys/SiteSetting.cs, src/Ops.Service/IncidentService.cs, src/Ops.Service/Interfaces/Ops/Repositories/ITitleClassRepository.cs, src/Ops.Service/Interfaces/Ops/Repositories/IUserRepository.cs, src/Ops.Service/Interfaces/Ops/Services/ITitleClassService.cs, src/Ops.Service/Interfaces/Ops/Services/IUserService.cs, src/Ops.Service/TitleClassService.cs, src/Ops.Service/UserService.cs, src/Ops.Web/Areas/ContentManagement/Views/Home/Index.cshtml, src/Ops.Web/Areas/ContentManagement/Views/Users/TitleClassDetails.cshtml, src/Ops.Web/Areas/ContentManagement/Views/Users/TitleClassList.cshtml, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Startup.cs, src/Ops.Web/Views/Profile/Index.cshtml, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Email/Sender.cs
- Add title based classification
- Improve incident emails
=> Improve incident emails

src/Ops.Controllers/Areas/SiteManagement/HomeController.cs, src/Ops.Controllers/Areas/SiteManagement/PagesController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Pages/IndexViewModel.cs, src/Ops.Web/Areas/SiteManagement/Views/Pages/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
PR #476 allows admins with the `WebPageContentManagement` to edit all pages. This PR allows them to see edit buttons on each page.
=> Fix Web Content permission to see pages

src/Ops.Web/Areas/SiteManagement/Views/Locations/_AddFeaturesPartial.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Locations/_AddGroupsPartial.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
=> Fix add location feature pagination

src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/StatusController.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Status/Index.cshtml
=> Add product index to Promenade

src/Ops.Controllers/Areas/SiteManagement/ImageFeaturesController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/ImageFeatures/DetailViewModel.cs, src/Ops.Data/Promenade/ImageFeatureTemplateRepository.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20220819193002_prom_v1.0.0.201.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20220819193002_prom_v1.0.0.201.cs, src/Ops.Service/ImageFeatureService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/IImageFeatureTemplateRepository.cs, src/Ops.Service/Interfaces/Promenade/Services/IImageFeatureService.cs, src/Ops.Web/Areas/SiteManagement/Views/ImageFeatures/Detail.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Models/Entities/ImageFeatureTemplate.cs, src/Promenade.Web/Promenade.Web.csproj
- Add management of page image feature templates
- Institute maximum size for image features
=> Add management of page image feature templates

src/Ops.Models/Entities/User.cs, src/Ops.Service/LdapService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
Pull fields:
- mobile
- department
=> Pull extra LDAP fields

src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs, src/Ops.Data/Promenade/LocationProductMapRepository.cs, src/Ops.Data/Promenade/LocationRepository.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20230203222646_prom_v1.0.0.223.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20230203222646_prom_v1.0.0.223.cs, src/Ops.Service/Filters/BaseFilter.cs, src/Ops.Service/Filters/LocationFilter.cs, src/Ops.Service/Interfaces/Ops/Services/ILocationService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/ILocationProductMapRepository.cs, src/Ops.Service/Interfaces/Promenade/Repositories/ILocationRepository.cs, src/Ops.Service/LocationService.cs, src/Ops.Web/Areas/SiteManagement/Views/Locations/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/StatusController.cs, src/Promenade.Data/Promenade/LocationRepository.cs, src/Promenade.Models/Entities/Location.cs, src/Promenade.Web/Promenade.Web.csproj
- Flag locations as deleted rather than deleting them
- Remove related items
=> Improve ability to delete locations

src/Ops.Controllers/Areas/Incident/HomeController.cs, src/Ops.Controllers/Areas/Incident/ViewModel/DetailsViewModel.cs, src/Ops.Controllers/Areas/Incident/ViewModel/IndexViewModel.cs, src/Ops.Data/Promenade/LocationRepository.cs, src/Ops.Service/Interfaces/Ops/Services/ILocationService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/ILocationRepository.cs, src/Ops.Service/LocationService.cs, src/Ops.Web/Areas/Incident/Views/Home/Details.cshtml, src/Ops.Web/Areas/Incident/Views/Home/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
=> Update to show deleted incident locations

src/Ops.Controllers/ProfileController.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20230428223635_ops_v1.0.0.234.Designer.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20230428223635_ops_v1.0.0.234.cs, src/Ops.Models/Entities/User.cs, src/Ops.Service/Interfaces/Ops/Services/IUserService.cs, src/Ops.Service/LdapService.cs, src/Ops.Service/UserService.cs, src/Ops.Service/UserSyncService.cs, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Views/Profile/Index.cshtml, src/Promenade.Web/Promenade.Web.csproj
- Fix bug with multiple direct reports
- Improve associated location override functionality
=> Improve LDAP sync

Dockerfile_ops, Dockerfile_promenade, docker-lock.json, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Update packages for .NET 7.0.9
- Update Docker lock checksums
- Quiet Docker test and release builds (`-v m` and `/property:WarningLevel=0`)
=> Update packages; quiet build in Docker

src/Ops.Controllers/Areas/SiteManagement/DecksController.cs, src/Ops.Data/Promenade/DeckRepository.cs, src/Ops.Service/DeckService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/IDeckRepository.cs
- Add logging for deck permission issues
- Fix ordering issue when a card is deleted
=> Improve card handling

src/Ops.Controllers/Areas/SiteManagement/DecksController.cs, src/Ops.Data/Promenade/CardRepository.cs, src/Ops.Service/DeckService.cs, src/Ops.Web/Areas/SiteManagement/Views/Decks/Card.cshtml
- Fix increment logic
- Fix order-of-operations issue with add card ordering
- Fix bug with missing deck id for add card image
=> Improve deck/card code

docker-lock.json, src/Ops.Controllers/Areas/SiteManagement/DecksController.cs, src/Ops.Controllers/Areas/SiteManagement/HomeController.cs, src/Ops.Controllers/Areas/SiteManagement/ImageFeaturesController.cs, src/Ops.Controllers/Areas/SiteManagement/ImageOptimizerController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Home/IndexViewModel.cs, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Models/Definitions/ApplicationPermissionDefinitions.cs, src/Ops.Models/Keys/ApplicationPermission.cs, src/Ops.Service/ImageService.cs, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Areas/SiteManagement/Views/Home/Index.cshtml, src/Ops.Web/Areas/SiteManagement/Views/ImageOptimizer/Index.cshtml, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Exceptions/OcudaConfigurationException.cs, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Add OcudaConfigurationException
- Handle missing optimizer configuration for inlined image optimization
- Add ImageOptimizer application permission
- Improve manual image optimizer interface
=> Improve image optimization

src/Ops.Controllers/Areas/SiteManagement/PagesController.cs, src/Ops.Controllers/Areas/SiteManagement/ViewModels/Pages/LayoutsViewModel.cs, src/Ops.Web/Areas/SiteManagement/Views/Pages/LayoutDetail.cshtml, src/Ops.Web/Areas/SiteManagement/Views/Pages/Layouts.cshtml, src/Promenade.Controllers/Abstract/BasePageController.cs, src/Promenade.Controllers/Abstract/GeneralBasePageController.cs, src/Promenade.Controllers/HomeController.cs, src/Promenade.Web/Views/Shared/LayoutPage.cshtml, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Fix homepage previews
- Better handle invalid preview requests
- Allow previewing from the layout list
- Change preview icon to magnifying glass
- Update test packages
=> Improve page previews; update test packages

src/Ops.Controllers/Areas/Incident/HomeController.cs, src/Ops.Service/IncidentService.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj
- Don't fail on adding incident if notifying a nonexistent user
- Don't allow incidents for days later than today
=> Fix bug with incident notifications

src/Ops.Controllers/Areas/Incident/HomeController.cs, src/Ops.Controllers/Areas/Incident/ViewModel/ConfigurationViewModel.cs, src/Ops.Controllers/Areas/Incident/ViewModel/IncidentViewModelBase.cs, src/Ops.Controllers/Areas/Incident/ViewModel/PermissionsViewModel.cs, src/Ops.Data/Ops/IncidentRepository.cs, src/Ops.Data/Ops/PermissionGroupIncidentLocationRepository.cs, src/Ops.Data/OpsContext.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20240919022935_ops_v1.0.0.288.Designer.cs, src/Ops.DataProvider.SqlServer.Ops/Migrations/20240919022935_ops_v1.0.0.288.cs, src/Ops.Models/Entities/PermissionGroupApplication.cs, src/Ops.Models/Entities/PermissionGroupIncidentLocation.cs, src/Ops.Service/IncidentService.cs, src/Ops.Service/Interfaces/Ops/Repositories/IPermissionGroupIncidentLocationRepository.cs, src/Ops.Service/PermissionGroupService.cs, src/Ops.Web/Areas/Incident/Views/Home/Configuration.cshtml, src/Ops.Web/Areas/Incident/Views/Home/Permissions.cshtml, src/Ops.Web/Areas/Incident/Views/Shared/_IncidentPartial.cshtml, src/Ops.Web/Startup.cs, src/Ops.Web/Views/Shared/_Layout.cshtml, src/Utility/Keys/Cache.cs
Add permission group mapping to see incidents at specific locations
=> Add incident location permissions

docker-lock.json, src/Ops.Controllers/Areas/Incident/HomeController.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Fix individual incident display if staff member has location-based permissions
- Update xunit package
- Update Docker lock checksums
=> Fix location-based incident display permissions

src/Ops.Service/Ops.Service.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj, src/SlideUploader/SlideUploader.csproj, src/Utility/Utility.csproj
- Update MailKit 4.7.1.1 -> 4.8
- Update Serilog 4.0.1 -> 4.0.2
=> Update packages: Serilog, MailKit

docker-lock.json, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Service/Ops.Service.csproj, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Service/Promenade.Service.csproj, src/Promenade.Web/Promenade.Web.csproj, src/SlideUploader/SlideUploader.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
- Microsoft.AspNetCore.DataProtection 8.0.8 -> 8.0.10
- Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 8.0.8 -> 8.0.10
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 8.0.8 -> 8.0.10
- Microsoft.EntityFrameworkCore 8.0.8 -> 8.0.10
- Microsoft.EntityFrameworkCore.InMemory 8.0.8 -> 8.0.10
- Microsoft.EntityFrameworkCore.Relational 8.0.8 -> 8.0.10
- Microsoft.EntityFrameworkCore.SqlServer 8.0.8 -> 8.0.10
- Microsoft.EntityFrameworkCore.Tools 8.0.8 -> 8.0.10
- Microsoft.Extensions.Caching.StackExchangeRedis 8.0.8 -> 8.0.10
- Microsoft.Extensions.Configuration.UserSecrets 8.0.0 -> 8.0.1
- Microsoft.Extensions.Logging 8.0.0 -> 8.0.1
- NLayer 1.15.0 -> 1.16.0
- Serilog.Settings.Configuration 8.0.2 -> 8.0.4
=> Update packages; Docker lock checksums

Dockerfile_ops, Dockerfile_promenade, docker-lock.json, src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Service/Ops.Service.csproj, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- LigerShark.WebOptimizer.Core 3.0.426 -> 3.0.433
- Microsoft.AspNetCore.DataProtection 8.0.10 -> 8.0.11
- Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 8.0.10 -> 8.0.11
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 8.0.10 -> 8.0.11
- Microsoft.EntityFrameworkCore 8.0.10 -> 8.0.11
- Microsoft.EntityFrameworkCore.InMemory 8.0.10 -> 8.0.11
- Microsoft.EntityFrameworkCore.Relational 8.0.10 -> 8.0.11
- Microsoft.EntityFrameworkCore.SqlServer 8.0.10 -> 8.0.11
- Microsoft.EntityFrameworkCore.Tools 8.0.10 -> 8.0.11
- Microsoft.Extensions.Caching.StackExchangeRedis 8.0.10 -> 8.0.11
- Microsoft.NET.Test.Sdk 17.11.1 -> 17.12.0
- NUglify 1.21.9 -> 1.21.10
- SixLabors.ImageSharp 3.1.5 -> 3.1.6
=> Update packages, pinned curl, Docker checksums

src/Ops.Controllers/Areas/ContentManagement/DigitalDisplaysController.cs, src/Ops.Controllers/Areas/ContentManagement/ViewModels/DigitalDisplays/CurrentDisplayAssetsViewModel.cs, src/Ops.Controllers/LocationsController.cs, src/Ops.Controllers/ViewModels/Locations/DetailsViewModel.cs, src/Ops.Data/Ops/DigitalDisplayRepository.cs, src/Ops.Service/DigitalDisplayService.cs, src/Ops.Service/Interfaces/Ops/Repositories/IDigitalDisplayRepository.cs, src/Ops.Service/Interfaces/Ops/Services/IDigitalDisplayService.cs, src/Ops.Web/Areas/Contact/Views/Schedule/Index.cshtml, src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/Assets.cshtml, src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/CurrentDisplayAssets.cshtml, src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/Index.cshtml, src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/Sets.cshtml, src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/_DigitalDisplaysPartial.cshtml, src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/_UploadImagePartial.cshtml, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Views/Locations/Details.cshtml, src/Promenade.Web/Promenade.Web.csproj
- Add link from location in MC to digital displays
- Add more buttons to upload digital display assets
=> Improve digital display image upload access

docker-lock.json, src/SlideUploader/SlideUploader.csproj
=> Update packages, Docker lock checksums

src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Service/DeckService.cs, src/Ops.Service/Ops.Service.csproj, src/Ops.Web/Ops.Web.csproj, src/Ops.Web/Program.cs, src/Promenade.Web/Program.cs, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj
- Include footer on cards when cloning layouts that contain them
- Fix shutdown message formatting to match startup message formatting
=> Include footer on card clone; fix shutdown message

src/Ops.Service/Ops.Service.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj
=> Update MailKit package

docker-lock.json, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20250212214349_prom_v1.0.0.303.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20250212214349_prom_v1.0.0.303.cs, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Models/Entities/EmediaText.cs, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- Add characters to digital library description (from 512 to 1000)
- Update Docker lock checksums
- Microsoft.AspNetCore.DataProtection 8.0.12 -> 8.0.13
- Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 8.0.12 -> 8.0.13
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 8.0.12 -> 8.0.13
- Microsoft.EntityFrameworkCore 8.0.12 -> 8.0.13
- Microsoft.EntityFrameworkCore.InMemory 8.0.12 -> 8.0.13
- Microsoft.EntityFrameworkCore.Relational 8.0.12 -> 8.0.13
- Microsoft.EntityFrameworkCore.SqlServer 8.0.12 -> 8.0.13
- Microsoft.EntityFrameworkCore.Tools 8.0.12 -> 8.0.13
- Microsoft.Extensions.Caching.StackExchangeRedis 8.0.12 -> 8.0.13
- Microsoft.NET.Test.Sdk 17.12.0 -> 17.13.0
- xunit.runner.visualstudio 3.0.1 -> 3.0.2
=> Add characters to digital library; update packages

src/Ops.Service/Ops.Service.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/Abstract/BasePageController.cs, src/Promenade.Controllers/PodcastsController.cs, src/Promenade.Controllers/ViewModels/Shared/PageLayoutViewModel.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/Help/Schedule.cshtml, src/Promenade.Web/Views/Help/ScheduleDetails.cshtml, src/Promenade.Web/Views/Help/ScheduleTimes.cshtml, src/Promenade.Web/Views/Home/AdultVolunteerForm.cshtml, src/Promenade.Web/Views/Home/Feature.cshtml, src/Promenade.Web/Views/Home/Location.cshtml, src/Promenade.Web/Views/Home/TeenVolunteerForm.cshtml, src/Promenade.Web/Views/Locations/Index.cshtml, src/Promenade.Web/Views/Podcasts/Episode.cshtml, src/Promenade.Web/Views/Podcasts/Index.cshtml, src/Promenade.Web/Views/Podcasts/Podcast.cshtml, src/Promenade.Web/Views/Podcasts/ShowNotes.cshtml, src/Promenade.Web/Views/Shared/LayoutPage.cshtml, src/Promenade.Web/Views/Status/Index.cshtml, src/Promenade.Web/Views/Status/Product.cshtml, src/Utility/Utility.csproj, src/i18n/RouteConstraint/CultureRouteConstraint.cs
- Update MailKit 4.10.0 -> 4.11.0
- Update Promenade to exclude culture when generating links
- Change localization to be case-insensitive
=> Fix links to not include culture; update MailKit

Dockerfile_ops, Dockerfile_promenade, docker-lock.json, src/Ops.Data/Promenade/CarouselButtonLabelRepository.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20250326235259_prom_v1.0.0.307.Designer.cs, src/Ops.DataProvider.SqlServer.Promenade/Migrations/20250326235259_prom_v1.0.0.307.cs, src/Ops.Service/CarouselService.cs, src/Ops.Service/Interfaces/Promenade/Repositories/ICarouselButtonLabelRepository.cs, src/Ops.Web/Ops.Web.csproj, src/Promenade.Controllers/ViewModels/Shared/PageLayoutViewModel.cs, src/Promenade.Models/Entities/CarouselButtonLabel.cs, src/Promenade.Web/Promenade.Web.csproj, src/Promenade.Web/Views/DigitalLibrary/Index.cshtml, src/Promenade.Web/Views/Shared/LayoutPage.cshtml
- Add ability to disable carousel button types
- Revise digital library card formatting
- Update Docker lock checksums
- Update pinned curl version
=> Add ability to disable carousel button types

docker-lock.json, src/Ops.Controllers/Ops.Controllers.csproj, src/Ops.Data/Ops.Data.csproj, src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj, src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj, src/Ops.Service/Ops.Service.csproj, src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Data/Promenade.Data.csproj, src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj, src/Promenade.Web/Promenade.Web.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- LigerShark.WebOptimizer.Core 3.0.433 -> 3.0.436
- MailKit 4.11.0 -> 4.12.0
- Microsoft.AspNetCore.DataProtection 8.0.14 -> 8.0.15
- Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 8.0.14 -> 8.0.15
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 8.0.14 -> 8.0.15
- Microsoft.EntityFrameworkCore 8.0.14 -> 8.0.15
- Microsoft.EntityFrameworkCore.InMemory 8.0.14 -> 8.0.15
- Microsoft.EntityFrameworkCore.Relational 8.0.14 -> 8.0.15
- Microsoft.EntityFrameworkCore.SqlServer 8.0.14 -> 8.0.15
- Microsoft.EntityFrameworkCore.Tools 8.0.14 -> 8.0.15
- Microsoft.Extensions.Caching.StackExchangeRedis 8.0.14 -> 8.0.15
- NUglify 1.21.13 -> 1.21.15
- SixLabors.ImageSharp 3.1.7 -> 3.1.8
- xunit.runner.visualstudio 3.0.2 -> 3.1.0
=> Update packages, Docker lock checksum

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/cr-cleanup.yml, .github/workflows/docker-lock-verify.yml, .github/workflows/dotnet-outdated.yml, docker-lock.json, ocuda.sln, src/Ops.Service/Ops.Service.csproj, src/Ops.Web/Ops.Web.csproj, src/Promenade.Web/Promenade.Web.csproj, src/SlideUploader/SlideUploader.csproj, src/Utility/Utility.csproj, test/Ops/Ops.Data.Test/Ops.Data.Test.csproj, test/i18n/i18n.Test/i18n.Test.csproj
- MailKit 4.12.0 -> 4.12.1
- Microsoft.NET.Test.Sdk 17.13.0 -> 17.14.0
- Serilog 4.2.0 -> 4.3.0
=> Update packages; Docker lock checksums; actions
